GET http://localhost:3000/parks
Content-Type: application/json

{
    "lat": 39.7392,
    "lng": -104.9903,
    "radius": 1000000000000000

}

###
POST http://localhost:3000/parks
Content-Type: application/json

{
    "address": {
        "street": "1234 Main St",
        "city": "Denver",
        "state": {
            "fullName": "Colorado",
            "abbreviation": "CO"
        },
        "zipCode": "80202", 
        "neighborhood": "LoDo",
        "number": "1234567890"
    
    }, 
    "coordinates": [39.7392, -104.9903],
    "parkName": "Wyoming",
    "capacity": 20,
    "currentPlayers": 10
}
###
GET http://localhost:3000/parks/6502248752d2775c4a069052

###
DELETE http://localhost:3000/parks/65011d4061912b4949d15c36

###
GET http://localhost:3000/parks/6502248752d2775c4a069052/thumbnail

// MATCHES

###
GET http://localhost:3000/matches

###
POST http://localhost:3000/matches
Content-Type: application/json

{
    "parkId": "6502248752d2775c4a069052",
    "courtId": "974129843729",
    "players": [],
    "date": "2021-09-01T00:00:00.000Z",
    "note": "any n testttote"
}

###
GET http://localhost:3000/matches/6502370003780e82227f3d27

###
DELETE http://localhost:3000/matches/6502370003780e82227f3d27

// COURTS

###
GET http://localhost:3000/courts

###
POST http://localhost:3000/courts
Content-Type: application/json

{
    "parkId": "6502370003780e82227f3d27",
    "courtName": "Court 1",
    "courtType": "Indoor",
    "courtNumber": 1,
    "courtDescription": "test"
}

###
GET http://localhost:3000/courts/park/6502370003780e82227f3d27

//pictures

###
GET http://localhost:3000/pictures/650240821e5839d2e3d18db8

###
POST http://localhost:3000/pictures
Content-Type: application/json

{
    "url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nba.com%2Fnews%2Ffeatures%2Ftop-10-plays-of-the-week%2F&psig=AOvVaw0QZQ4Z4Z3Z4Z3Z4Z3Z4Z3Z4&ust=1629989850000000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ9ZqH9_ICFQAAAAAdAAAAABAD",
    "alt": "test",
    "parentId": "6502370003780e82227f3d27",
    "module": "court" 
}

###
DELETE http://localhost:3000/pictures/65023fd505804be100405ee9


// auth
//register
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "any@any.com",
    "password": "test"
}

//login 
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "any@any.com",
    "password": "test"
}
//logout
###
DELETE http://localhost:3000/auth/logout



